const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("wm", {
  read: (kind) => ipcRenderer.invoke("config:read", kind),
  write: (kind, text) => ipcRenderer.invoke("config:write", kind, text),
  validate: (kind, text) => ipcRenderer.invoke("config:validate", kind, text),
  status: () => ipcRenderer.invoke("status:get"),
  restart: (name) => ipcRenderer.invoke("service:restart", name),
  komorebic: (args) => ipcRenderer.invoke("komorebic:run", args),
  reveal: (kind) => ipcRenderer.invoke("file:reveal", kind),
  restore: (kind, backupPath) => ipcRenderer.invoke("config:restore", kind, backupPath),
  confirm: (message, detail) => ipcRenderer.invoke("dialog:confirm", message, detail),
  snapshots: () => ipcRenderer.invoke("snapshot:list"),
  snapshotSave: (name) => ipcRenderer.invoke("snapshot:save", name),
  snapshotRestore: (name) => ipcRenderer.invoke("snapshot:restore", name),
  snapshotDelete: (name) => ipcRenderer.invoke("snapshot:delete", name),
  pickImage: () => ipcRenderer.invoke("dialog:pickImage"),
  currentWallpaper: () => ipcRenderer.invoke("wallpaper:current"),
  profiles: () => ipcRenderer.invoke("profile:list"),
  profileSave: (name) => ipcRenderer.invoke("profile:save", name),
  profileApply: (name) => ipcRenderer.invoke("profile:apply", name),
  profileDelete: (name) => ipcRenderer.invoke("profile:delete", name),
  health: () => ipcRenderer.invoke("health:check"),
  commands: () => ipcRenderer.invoke("komorebic:commands"),
  schema: () => ipcRenderer.invoke("komorebic:schema"),
  setupCheck: () => ipcRenderer.invoke("setup:check"),
  setupLocate: (key) => ipcRenderer.invoke("setup:locate", key),
  windows: () => ipcRenderer.invoke("windows:list"),
  apps: () => ipcRenderer.invoke("apps:list"),
  state: () => ipcRenderer.invoke("komorebi:state"),
  moveWindow: (hwnd, rect) => ipcRenderer.invoke("window:move", hwnd, rect),
  onTop: (on) => ipcRenderer.invoke("window:onTop", on),
  startEvents: () => ipcRenderer.invoke("events:start"),
  onEvent: (fn) => ipcRenderer.on("komorebi:event", () => fn()),
  diff: (kind, next) => ipcRenderer.invoke("config:diff", kind, next),
});
