/* Every YASB widget type, resolved from the amnweb/yasb source and
   verified against the types already working in this config.
   Regenerate after a YASB upgrade rather than editing by hand. */

window.YASB_WIDGETS = [
  { type: "glazewm.binding_mode.GlazewmBindingModeWidget", label: "Binding Mode", ns: "glazewm" },
  { type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget", label: "Tiling Direction", ns: "glazewm" },
  { type: "glazewm.workspaces.GlazewmWorkspacesWidget", label: "Workspaces", ns: "glazewm" },
  { type: "komorebi.active_layout.ActiveLayoutWidget", label: "Active Layout", ns: "komorebi" },
  { type: "komorebi.control.KomorebiControlWidget", label: "Control", ns: "komorebi" },
  { type: "komorebi.stack.StackWidget", label: "Stack", ns: "komorebi" },
  { type: "komorebi.workspaces.WorkspaceWidget", label: "Workspaces", ns: "komorebi" },
  { type: "yasb.active_window.ActiveWindowWidget", label: "Active Window", ns: "yasb" },
  { type: "yasb.applications.ApplicationsWidget", label: "Applications", ns: "yasb" },
  { type: "yasb.battery.BatteryWidget", label: "Battery", ns: "yasb" },
  { type: "yasb.bluetooth.BluetoothWidget", label: "Bluetooth", ns: "yasb" },
  { type: "yasb.brightness.BrightnessWidget", label: "Brightness", ns: "yasb" },
  { type: "yasb.cava.CavaWidget", label: "Cava", ns: "yasb" },
  { type: "yasb.claude_usage.ClaudeUsageWidget", label: "Claude Usage", ns: "yasb" },
  { type: "yasb.clock.ClockWidget", label: "Clock", ns: "yasb" },
  { type: "yasb.codex_usage.CodexUsageWidget", label: "Codex Usage", ns: "yasb" },
  { type: "yasb.control_center.ControlCenterWidget", label: "Control Center", ns: "yasb" },
  { type: "yasb.copilot.CopilotWidget", label: "Copilot", ns: "yasb" },
  { type: "yasb.cpu.CpuWidget", label: "CPU", ns: "yasb" },
  { type: "yasb.custom.CustomWidget", label: "Custom", ns: "yasb" },
  { type: "yasb.disk.DiskWidget", label: "Disk", ns: "yasb" },
  { type: "yasb.dnd.DndWidget", label: "Do Not Disturb", ns: "yasb" },
  { type: "yasb.github.GithubWidget", label: "Github", ns: "yasb" },
  { type: "yasb.gpu.GpuWidget", label: "GPU", ns: "yasb" },
  { type: "yasb.grouper.GrouperWidget", label: "Grouper", ns: "yasb" },
  { type: "yasb.home.HomeWidget", label: "Home", ns: "yasb" },
  { type: "yasb.language.LanguageWidget", label: "Language", ns: "yasb" },
  { type: "yasb.launchpad.LaunchpadWidget", label: "Launchpad", ns: "yasb" },
  { type: "yasb.libre_monitor.LibreHardwareMonitorWidget", label: "Libre Monitor", ns: "yasb" },
  { type: "yasb.media.MediaWidget", label: "Media", ns: "yasb" },
  { type: "yasb.media_lite.MediaWidget", label: "Media Lite", ns: "yasb" },
  { type: "yasb.memory.MemoryWidget", label: "Memory", ns: "yasb" },
  { type: "yasb.microphone.MicrophoneWidget", label: "Microphone", ns: "yasb" },
  { type: "yasb.notes.NotesWidget", label: "Notes", ns: "yasb" },
  { type: "yasb.notifications.NotificationsWidget", label: "Notifications", ns: "yasb" },
  { type: "yasb.obs.ObsWidget", label: "OBS", ns: "yasb" },
  { type: "yasb.open_meteo.OpenMeteoWidget", label: "Open Meteo", ns: "yasb" },
  { type: "yasb.pomodoro.PomodoroWidget", label: "Pomodoro", ns: "yasb" },
  { type: "yasb.power_menu.PowerMenuWidget", label: "Power Menu", ns: "yasb" },
  { type: "yasb.power_plan.PowerPlanWidget", label: "Power Plan", ns: "yasb" },
  { type: "yasb.quick_launch.QuickLaunchWidget", label: "Quick Launch", ns: "yasb" },
  { type: "yasb.recycle_bin.RecycleBinWidget", label: "Recycle Bin", ns: "yasb" },
  { type: "yasb.systray.SystrayWidget", label: "Systray", ns: "yasb" },
  { type: "yasb.taskbar.TaskbarWidget", label: "Taskbar", ns: "yasb" },
  { type: "yasb.todo.TodoWidget", label: "Todo", ns: "yasb" },
  { type: "yasb.traffic.TrafficWidget", label: "Traffic", ns: "yasb" },
  { type: "yasb.update_check.UpdateCheckWidget", label: "Update Check", ns: "yasb" },
  { type: "yasb.volume.VolumeWidget", label: "Volume", ns: "yasb" },
  { type: "yasb.vscode.VSCodeWidget", label: "VS Code", ns: "yasb" },
  { type: "yasb.wallpapers.WallpapersWidget", label: "Wallpapers", ns: "yasb" },
  { type: "yasb.weather.WeatherWidget", label: "Weather", ns: "yasb" },
  { type: "yasb.whkd.WhkdWidget", label: "WHKD", ns: "yasb" },
  { type: "yasb.wifi.WifiWidget", label: "WiFi", ns: "yasb" },
  { type: "yasb.window_controls.WindowControlsWidget", label: "Window Controls", ns: "yasb" },
  { type: "yasb.window_switcher.WindowSwitcherWidget", label: "Window Switcher", ns: "yasb" },
  { type: "yasb.windows_desktops.WorkspaceWidget", label: "Windows Desktops", ns: "yasb" },
];
